// Bundles the Markdown in content/ into src/generated/content.ts so pages don't read files at runtime.
// (Cloudflare Workers have no project folder to read from while running.)
// Runs automatically before dev, build, test and the vinext (Cloudflare) scripts. Run `npm run content`
// after adding or editing a post if the dev server is already running.
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const readDir = (dir) => {
  const full = path.join(root, "content", dir);
  if (!fs.existsSync(full)) return {};
  return Object.fromEntries(
    fs
      .readdirSync(full)
      .filter((f) => f.endsWith(".md"))
      .sort()
      .map((f) => [f.replace(/\.md$/, ""), fs.readFileSync(path.join(full, f), "utf8").replace(/\r\n/g, "\n")]),
  );
};

const out = `// GENERATED by scripts/build-content.mjs from content/*.md. Do not edit; it is git-ignored.
export const insightFiles: Record<string, string> = ${JSON.stringify(readDir("insights"), null, 2)};

export const playbookFiles: Record<string, string> = ${JSON.stringify(readDir("playbooks"), null, 2)};
`;

const target = path.join(root, "src", "generated", "content.ts");
fs.mkdirSync(path.dirname(target), { recursive: true });
if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== out) fs.writeFileSync(target, out);
console.log(`content: ${Object.keys(readDir("insights")).length} post(s), ${Object.keys(readDir("playbooks")).length} playbook(s)`);
